# -*- coding: utf-8 -*-
"""CIS412 Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jm1UHYCSv4T3-TFSsxnFTpnSEmMD2xmO
"""

import pandas as pd
df = pd.read_csv("/content/superstore_data.csv")

df.head()
df.shape
df.info()
df.describe()

df.head()

df.isnull().sum()

#Handle Null Values
df['Income'] = df['Income'].fillna(df['Income'].median())

#Convert to age
import datetime

current_year = datetime.datetime.now().year
df['Age'] = current_year - df['Year_Birth']

df = df.drop('Year_Birth', axis=1)

#Remove unrealistic ages
df = df[(df['Age'] > 18) & (df['Age'] < 90)]

#Converting dt customer to tenure
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'])

df['Customer_Tenure'] = (pd.Timestamp.now() - df['Dt_Customer']).dt.days

df = df.drop('Dt_Customer', axis=1)

#Create total spending
spending_cols = [
    'MntWines','MntFruits','MntMeatProducts',
    'MntFishProducts','MntSweetProducts','MntGoldProds'
]

df['Total_Spending'] = df[spending_cols].sum(axis=1)

# Create total purchases
df['Total_Purchases'] = (
    df['NumWebPurchases'] +
    df['NumCatalogPurchases'] +
    df['NumStorePurchases']
)

df = df.drop('Id', axis=1)

# Dummy Encoding
df = pd.get_dummies(df, columns=['Education', 'Marital_Status'], drop_first=True)

#Checking target
df['Response'].value_counts()

import matplotlib.pyplot as plt

counts = df['Response'].value_counts().sort_index()

plt.figure(figsize=(6,4))
counts.plot(kind='bar')
plt.title('Class Imbalance in Response')
plt.xlabel('Response Class')
plt.ylabel('Number of Customers')
plt.xticks([0, 1], ['0 = No', '1 = Yes'], rotation=0)
plt.show()

# Train.Test split
from sklearn.model_selection import train_test_split

X = df.drop('Response', axis=1)
y = df['Response']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

#Logistic Regression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train, y_train)

from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Random Forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(class_weight='balanced', random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print(classification_report(y_test, y_pred_rf))

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix

gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

print(confusion_matrix(y_test, y_pred_gb))
print(classification_report(y_test, y_pred_gb))

importance_gb = pd.Series(gb.feature_importances_, index=X.columns)
importance_gb.sort_values(ascending=False).head(10)

import matplotlib.pyplot as plt

importance_gb.sort_values(ascending=False).head(10).plot(kind='barh')
plt.title("Top Features Influencing Customer Response")
plt.gca().invert_yaxis()
plt.show()